services:
  db:
    image: mysql:8.4.0
    env_file:
      - .env
    ports:
      - 3306:3306
    networks:
      - spring-network
    volumes:
      - data:/var/lib/mysql

  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge

volumes:
  data:
