services:
  db:
    image: mysql:8.4.0
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api-rest-spring
    ports:
      - 3306:3306
    networks:
      - spring-network
    volumes:
      - data:/var/lib/mysql

  api-rest-spring:
    build:
      context: .
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/api-rest-spring?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: root
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge

volumes:
  data:
