server:
  port: 80

cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://anthonycruz.com.br

file:
  upload-dir: /upload-spring-api

security:
  jwt:
    token:
      secret-key: Y-jmkvqIX-ybBZJslz2B8CREZRQvbn8qCsP6Y2KVxSc
      expire-length: 3600000

spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      # url: jdbc:mysql://localhost:3306/api-rest-spring?useTimezone=true&serverTimezone=UTC
      # username: root
      # password: root
      url: jdbc:mysql://api-rest-spring.c3uioyue80xs.us-east-1.rds.amazonaws.com:3306/api_database?useTimezone=true&serverTimezone=UTC
      username: root
      password: rootroot
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

springdoc:
  paths-to-match:
    - /auth/**
    - /persons/**
    - /books/**
    - /files/**
  swagger-ui:
    use-root-path: true
