INSERT INTO `person` (`id`, `address`, `first_name`, `gender`, `last_name`) VALUES
	(1, 'Caçador/SC', 'Anthony', 'Male', 'Cruz'),
	(4, '221B Baker Street', 'Sherlock', 'M', 'Holmes'),
	(5, '12 Grimmauld Place', 'Hermione', 'F', 'Granger'),
	(6, '4 Privet Drive', 'Harry', 'M', 'Potter'),
	(7, '742 Evergreen Terrace', 'Homer', 'M', 'Simpson'),
	(8, '123 Fake Street', 'Peter', 'M', 'Griffin'),
	(9, '742 Evergreen Terrace', 'Marge', 'F', 'Simpson'),
	(10, '742 Evergreen Terrace', 'Bart', 'M', 'Simpson'),
	(11, '742 Evergreen Terrace', 'Lisa', 'F', 'Simpson'),
	(12, '31 Spooner Street', 'Stewie', 'M', 'Griffin'),
	(13, '742 Evergreen Terrace', 'Maggie', 'F', 'Simpson'),
	(14, '123 Elm Street', 'Freddy', 'M', 'Krueger'),
	(15, '221B Baker Street', 'John', 'M', 'Watson'),
	(16, '12 Grimmauld Place', 'Ron', 'M', 'Weasley'),
	(17, '4 Privet Drive', 'Dudley', 'M', 'Dursley'),
	(18, 'Bikini Bottom', 'SpongeBob', 'M', 'SquarePants'),
	(19, '742 Evergreen Terrace', 'Ned', 'M', 'Flanders'),
	(20, '742 Evergreen Terrace', 'Moe', 'M', 'Szyslak'),
	(21, '742 Evergreen Terrace', 'Maggie', 'F', 'Simpson'),
	(24, 'Test', 'Test', 'Female', 'Test');
